services:
    kalla-proxy:
      container_name: kalla-proxy
      build:
          context: .
          dockerfile: Dockerfile
      environment:
          - DATABASE_URL=file:./prisma/db/database.db
          - NEXTAUTH_SECRET=6ObFiRpsf9DTySxBjATdnrfHRmg7OSJnCvP6vqwx5CQ=
          - NEXTAUTH_URL=http://localhost:3000
          - AUTH_TRUST_HOST=true
          - HOSTNAME=0.0.0.0
          - TZ=Asia/Makassar
          - TRAEFIK_API_URL=http://localhost:8080
      ports:
          - "80:80"        # Traefik HTTP
      expose:
          - "3000"         # Next.js Dashboard
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - database_volume:/app/prisma/db
          - traefik_volume:/app/traefik
          - traefik_volume:/etc/traefik
      restart: unless-stopped

volumes:
    database_volume:
    traefik_volume: